from django.urls import path
from staff import views

urlpatterns = [
    path("", views.index, name="home"),
    path("registration-scanner/", views.registration_scanner, name="registration_scanner"),
    path("details-scanner/", views.details_scanner, name="details_scanner"),
    path("scanner-choice/", views.scanner_choice, name="scanner_choice"),
    path("security-scanner-entry/", views.security_scanner_entry, name="security_entry"),
    path("security-scanner-exit/", views.security_scanner_exit, name="security_exit"),
    path("conditions-scanner/", views.conditions_scanner, name="conditions_scanner"),
    path("search/", views.search, name="search"),
    path("statistics-in-venue/", views.statistics_in_venue, name="statistics_in_venue"),
    path("statistics-by-committee/", views.statistics_by_committee, name="statistics_by_committee"),
    path("statistics-not-registered/", views.statistics_not_registered, name="statistics_not_registered"),
    path("statistics-get-help/", views.statistics_get_help, name="statistics_get_help"),
    path("admin-tools/", views.admin_tools, name="admin_tools"),
    path("admin-count-reset-confirmation/", views.admin_count_reset_confirmation, name="admin_count_reset_confirmation"),
    path("admin-count-reset/", views.admin_count_reset, name="admin_count_reset"),
    path("admin-regenerate-confirmation/", views.admin_regenerate_confirmation, name="admin_regenerate_confirmation"),
    path("admin-regenerate/", views.admin_regenerate, name="admin_regenerate"),
    path("admin-register/", views.admin_register, name="admin_register"),
    path("admin-badge-export-confirmation/", views.admin_badge_export_confirmation, name="admin_badge_export_confirmation"),
    path("admin-badge-export/", views.admin_badge_export, name="admin_badge_export"),
    path("admin-database-check-confirmation/", views.admin_database_check_confirmation, name="admin_database_check_confirmation"),
    path("admin-database-check/", views.admin_database_check, name="admin_database_check"),
    path("admin-database-import-confirmation/", views.admin_database_import_confirmation, name='admin_database_import_confirmation'),
    path("admin-email-send-confirmation/", views.admin_email_send_confirmation, name="admin_email_send_confirmation"),
    path("admin-email-send/", views.admin_email_send, name="admin_email_send"),
    path("locked-out/", views.locked_out, name="locked_out"),
    path("admin-accounts-confirmation/", views.admin_accounts_confirmation,name="admin_accounts_confirmation"),
    path("schedules/", views.schedules, name="schedules"),
    path("voting-management/", views.voting_management, name="voting_management"),
    path("create-vote/", views.create_vote, name="create_vote"),
    path("manage-vote/", views.manage_vote, name="manage_vote"),
    path("frontend/auth/", views.frontend_index, name="frontend_index"),
    path("frontend/vote/", views.frontend_vote, name="frontend_vote"),
]
